version: '3.8'
services:
  report-service:
    container_name: report-service
    build:
      context: ../report-service
      dockerfile: Dockerfile
    image: report-service:latest
    ports:
      - 9050:9050
    networks:
      - ${GLOBAL_NETWORK:-gamestore}

  login-service:
    container_name: login-service
    build:
      context: ../customer-login-service
      dockerfile: Dockerfile
    image: customer-login-service:latest
    ports:
      - 9080:9080
    networks:
      - ${GLOBAL_NETWORK:-gamestore}

  customer-management-service:
    container_name: customer-management-service
    build:
      context: ../customer-management-service
      dockerfile: Dockerfile
    image: customer-management-service:latest
    ports:
      - 9070:9070
    networks:
      - ${GLOBAL_NETWORK:-gamestore}

  game-product-service:
    container_name: game-product-service
    build:
      context: ../game-product-service
      dockerfile: Dockerfile
    image: game-product-service:latest
    ports:
      - 9010:9010
    networks:
      - ${GLOBAL_NETWORK:-gamestore}

  game-purchase-service:
    container_name: game-purchase-service
    build:
      context: ../game-purchase-service
      dockerfile: Dockerfile
    image: game-purchase-service:latest
    ports:
      - 9090:9090
    networks:
      - ${GLOBAL_NETWORK:-gamestore}

  payment-service:
    container_name: payment-service
    build:
      context: ../payment-service
      dockerfile: Dockerfile
    image: payment-service:latest
    ports:
      - 9060:9060
    networks:
      - ${GLOBAL_NETWORK:-gamestore}