version: '3.8'
services:
  payment-service:
    container_name: payment-service
    environment:
      - spring_kafka_bootstrap_servers_list=kafka-broker-1:19092, kafka-broker-2:29092, kafka-broker-3:39092
      - kafka_schema_registry_url_key=schema.registry.url
      - kafka_schema_registry_url=http://schema-registry:8081
      - compression_type=snappy
      - kafka_producer_acks=all
    build:
      context: ../payment-service
      dockerfile: Dockerfile
    image: payment-service:latest
    ports:
      - 9060:9060
    networks:
      - ${GLOBAL_NETWORK:-gamestore}